id: PECC8D33C
initial_creation_type: ocr
source_metadata:
  volumes:
    b2914845a63f49e3a0962cdce7bf16fa:
      base_file: v096.txt
      image_group_id: I1PD95941
      title: ལྷོ་ཟ་མོ་ཚངས་དབྱངས་ལ་སྡུག་བསྔལ་གྱི་བྱེ་བྲག་བསྟན་པ།
      total_pages: 1144
      volume_number: 96
